// ───────────────────────────────────────────────────────────
// 手册页注册表（对标 Linux 的 man）。每条 = 名称 + 用法 + 说明。
// shell 的 `man <命令>` 读它；新增命令时顺手补一条即可。
// ───────────────────────────────────────────────────────────
export interface ManPage {
  title: string; // 一句话标题
  syn: string; // SYNOPSIS（用法）
  desc: string; // DESCRIPTION（可多句）
}

export const MAN: Record<string, ManPage> = {
  help: { title: '命令总览', syn: 'help [命令]', desc: '列出全部命令；带参数时等价于 man <命令>，显示该命令的手册页。' },
  man: { title: '查看手册页', syn: 'man [命令]', desc: '显示某命令的用法与说明。无参数时列出所有有手册页的命令。' },

  // 浏览 / 文件
  pwd: { title: '显示当前目录', syn: 'pwd', desc: '打印当前工作目录的绝对路径。' },
  ls: { title: '列目录内容', syn: 'ls [-l] [路径]', desc: '列出目录内容（目录在前）。-l 显示权限/属主/大小/修改时间。列根目录时附带虚拟挂载 proc/ dev/。' },
  cd: { title: '切换目录', syn: 'cd [路径]', desc: '改变当前工作目录。支持绝对/相对路径、. 与 ..。无参数回到根 /。不支持进入 /proc /dev 等虚拟目录。' },
  cat: { title: '查看/拼接内容', syn: 'cat [文件...]', desc: '打印文件内容。无文件参数时透传标准输入（配合管道）。读文件受权限位约束。' },
  echo: { title: '输出文本', syn: 'echo [文本...]', desc: '把参数原样输出（以空格连接）。支持 $VAR 变量替换。常配合 > 写文件。' },
  printf: { title: '格式化输出', syn: 'printf <格式串> [参数...]', desc: 'C 风格格式化输出。格式符：%s 字符串、%d/%i 整数、%f 浮点、%x/%X 十六进制、%o 八进制、%c 单字符、%% 百分号。转义：\\n \\t \\\\ \\r。格式串会循环消费参数直到用尽（多参数重复打印整段格式）。例：printf "%d+%d=%d\\n" 1 2 3 → 1+2=3。' },
  mkdir: { title: '新建目录', syn: 'mkdir <目录...>', desc: '创建一个或多个目录。父目录须已存在。' },
  touch: { title: '新建空文件', syn: 'touch <文件...>', desc: '创建不存在的空文件（已存在则不动）。' },
  rm: { title: '删除', syn: 'rm <路径...>', desc: '把文件/目录移入回收站（软删除，可在回收站还原）。不能删根目录。' },
  mv: { title: '移动/重命名', syn: 'mv <源> <目标>', desc: '目标是已存在目录则移入；否则按目标名重命名（可跨目录）。' },
  cp: { title: '复制', syn: 'cp <源文件> <目标>', desc: '复制文本文件。目标是目录则复制进去；否则按目标名新建。暂不支持二进制/目录。' },
  open: { title: '打开 App 或文件', syn: 'open <appId|路径>', desc: '是 App id 就启动该 App；是文件就用记事本/图片查看器打开；是目录就用文件管理器打开。由终端 open 启动的进程父进程为本终端。' },

  // 文本处理
  grep: { title: '按模式过滤行', syn: 'grep [-vinrcE] 模式 [文件...]', desc: '输出匹配（正则，非法则按字面量）的行。-i 忽略大小写、-n 显示行号、-r 递归目录、-v 反选、-c 只输出匹配行数（多文件每文件一行「文件:计数」，无匹配输出 0 码 1）、-E 扩展正则（JS 正则天然 ERE，仅兼容）。无文件读标准输入。有匹配退出码 0、无匹配 1。' },
  find: { title: '查找文件', syn: 'find [路径] [-name 通配] [-type f|d]', desc: '递归列出路径下的条目。-name 按文件名通配（* ? [a-z]）筛选、-type 限定文件/目录。默认从当前目录。' },
  wc: { title: '统计行/词/字符', syn: 'wc [-lwc] [文件]', desc: '统计行数/词数/字符数。无标志全显示。无文件读标准输入。' },
  head: { title: '取开头若干行', syn: 'head [-n N] [文件]', desc: '输出前 N 行（默认 10）。无文件读标准输入。' },
  tail: { title: '取结尾若干行', syn: 'tail [-n N] [文件]', desc: '输出后 N 行（默认 10）。无文件读标准输入。' },
  sort: { title: '排序行', syn: 'sort [-rn] [文件]', desc: '按行排序。-r 逆序、-n 数值排序。无文件读标准输入。' },
  uniq: { title: '去相邻重复行', syn: 'uniq [-c] [文件]', desc: '折叠相邻重复行。-c 在每行前加出现次数。常配合 sort 使用。' },
  cut: { title: '按列切取', syn: 'cut -d<分隔> -f<字段> [文件]', desc: '按分隔符切列取指定字段（-f1 或 -f1,3）。默认分隔符为制表符。无文件读标准输入。' },
  tr: { title: '字符变换', syn: 'tr [-cds] SET1 [SET2]', desc: '把 stdin 中 SET1 的字符映射到 SET2（按位对应，SET2 不足时取末字符）；-d 删除 SET1 字符、-s 压缩连续重复、-c 取 SET1 的补集（常与 -d 配合保留指定字符）。SET 支持区间 a-z、字符类 [:upper:]/[:lower:]/[:digit:]/[:alpha:]/[:alnum:]/[:space:]、转义 \\n \\t \\\\。例：echo "Hello" | tr "a-z" "A-Z" → HELLO；tr -d "\\n" 删所有换行；tr -dc "[:digit:]" 只保留数字。' },
  seq: { title: '数字序列', syn: 'seq [-w] <END>  |  seq [-w] <START> <END>  |  seq [-w] <START> <STEP> <END>', desc: '输出从 START 到 END（含）按 STEP 步进的数字序列，每行一个。单参数 START 默认为 1、步长默认 1；负数与浮点步长都支持。-w 等宽补零（按最大位数补前导 0）。常作 for 词表或配合 tr 把换行转空格。例：seq 3 → 1/2/3；seq 5 -1 1 → 5/4/3/2/1；seq -w 8 10 → 08/09/10。' },
  basename: { title: '取文件名', syn: 'basename <路径> [后缀]', desc: '输出路径的末段文件名（剥掉目录部分与尾随斜杠）。给后缀时同时剥掉该后缀。例：basename /a/b/c.txt → c.txt；basename /a/b/c.txt .txt → c。' },
  dirname: { title: '取目录名', syn: 'dirname <路径>', desc: '输出路径的目录部分（剥掉末段文件名）。根路径返回 /，无目录部分返回 .。例：dirname /a/b/c.txt → /a/b；dirname a/b → a；dirname hello → .。' },
  xargs: { title: '从 stdin 拼参数执行', syn: '命令 | xargs [-n N] [-I STR] <命令> [参数...]', desc: '从 stdin 按空白分词，把词作为参数追加到指定命令后执行。默认一次传入全部词（命令是 echo）；-n N 每 N 个词调用一次；-I STR 用 STR 占位符替换（每个词调用一次，命令中 STR 处填入该词）。仅支持内建命令（外部命令退出码 127）。空输入不调用命令（码 0）。退出码取最后一次调用的结果。例：find /etc -name "*.txt" | xargs grep 关键词；seq 3 | xargs -n 1 echo → 三次 echo。' },
  tee: { title: '分流 stdin', syn: '命令 | tee [-a] <文件...>', desc: '把 stdin 同时写到标准输出和一个或多个文件。-a 追加而非覆盖。常用于管道中留存中间结果。例：echo hi | tee a.txt b.txt → hi 写屏并落 a.txt/b.txt；echo more | tee -a a.txt → 追加到 a.txt。' },
  shift: { title: '参数移位', syn: 'shift [N]', desc: '在函数或 source 脚本内，把位置参数 $1/$2/… 左移 N 位（默认 1）：移位后 $1 取原 $N+1。N 超过当前参数数 → 退出码 1；shift 0 不移位（码 0）；函数/脚本外使用报错码 1。常用于 while 循环逐个消费 $@。例：f() { shift; echo "$@"; }; f a b c → b c。' },
  expr: { title: '表达式求值', syn: 'expr 表达式', desc: 'POSIX 风格表达式求值器，输出结果到 stdout。支持算术（+ - * / %，整除取整）、比较（< <= = == != >= >，返回 1/0）、逻辑（| 短路或、& 短路与）、括号分组。字符串函数：length 串、substr 串 起 长、index 串 字符集（返回首个命中位置，无命中 0）。: 正则匹配（ anchored，无捕获组返回匹配长度、有 \\( \\) 捕获组返回捕获内容）。运算符裸现（无左操作数）报错退出码 2；结果为空或 0 时退出码 1，否则 0。例：expr 3 + 4 → 7；expr length abcde → 5；expr abcdef : "a.c" → 3。' },
  tac: { title: '反向行序', syn: 'tac [文件]', desc: '把 stdin（或文件）按行逆序输出（最后一行变第一行）。与 cat 正相反。无文件参数读标准输入。例：printf "a\\nb\\nc" | tac → c/b/a。' },
  rev: { title: '每行字符反转', syn: 'rev [文件]', desc: '把每行的字符顺序反转后输出（行序不变）。中文按码点反转。无文件参数读标准输入。例：echo hello | rev → olleh；echo 你好 | rev → 好你。' },
  nl: { title: '行号标注', syn: 'nl [文件]', desc: '给每行加行号前缀（格式 "  行号  内容"）。默认空行不显示行号但占用逻辑行号（后续非空行号继续递增）。无文件参数读标准输入。例：printf "a\\nb\\nc" | nl → 1 a/2 b/3 c。' },
  column: { title: '列对齐表格化', syn: 'column -t [-s 分隔符] [文件]', desc: '-t 表格模式：按分隔符（默认连续空白）切列，列间以两空格拼接对齐输出。-s 指定分隔符（如 -s , 按逗号切）。非 -t 模式原样输出。无文件参数读标准输入。例：printf "a,b,c" | column -t -s , → a  b  c。' },
  sleep: { title: '延时执行', syn: 'sleep <N[s|m|h]>', desc: '延时指定秒数后返回。支持小数；后缀 s 秒（默认）、m 分（×60）、h 时（×3600）。0 立即返回。例：sleep 0.5; sleep 2m。' },
  yes: { title: '重复输出', syn: 'yes [字符串]', desc: '反复输出一行（默认 "y"）直到管道消费方关闭。本 shell 管道为快照模型无 SIGPIPE，内部封顶 1000 行防挂死。例：yes | head -3 → 三行 y。' },
  shuf: { title: '随机排列行', syn: 'shuf [-n N] [文件]  |  shuf -e 词…  |  shuf -i M-N', desc: '把输入行随机打乱输出。-n N 只输出前 N 行；-e 把参数作为行（而非文件）；-i M-N 生成 M..N 数字序列再打乱。无文件读标准输入。例：seq 5 | shuf -n 2 随机取两数。' },
  paste: { title: '按行合并文件', syn: 'paste [-d 分隔符] [-s] [文件...]', desc: '把多个文件的同行合并为一行，默认以 tab 分隔。-d 指定分隔符；-s 串行模式（每文件所有行合并成一行）。`-` 表示从标准输入读，多个 `-` 时按 round-robin 轮流分配 stdin 行。不等长文件用空串补齐。例：paste a b → a1\\tb1；printf "a\\nb\\nc\\nd" | paste - - → a\\tb / c\\td。' },
  comm: { title: '有序文件三列对比', syn: 'comm [-123] <文件1> <文件2>', desc: '逐行对比两个已排序文件，输出三列：第一列仅在文件1、第二列仅在文件2、第三列交集。列前导 tab 数 = 该列之前未隐藏列数（-1/-2/-3 隐藏对应列，可合并如 -12）。例：comm -12 a b 只显示交集；comm a b 默认三列（0/1/2 tab）。' },
  expand: { title: 'tab 转空格', syn: 'expand [-t N] [文件]', desc: '把 tab 展开为空格，按列位置对齐到下一个 tab 边界。-t N 指定 tab 宽度（默认 8）。无文件读标准输入。例：printf "a\\tb" | expand -t 4 → a   b。' },
  unexpand: { title: '空格转 tab', syn: 'unexpand [-t N] [文件]', desc: '把空格组转换为 tab：按列位置动态追踪 tab 边界，空格组每跨越一个 tab 边界即转换为一个 tab，剩余原样输出。-t N 指定 tab 宽度（默认 8）。无文件读标准输入。例：printf "a   b" | unexpand -t 4 → a\\tb。' },
  base64: { title: 'Base64 编解码', syn: 'base64 [-d]', desc: '从标准输入读数据进行 Base64 编码（默认）或解码（-d）。编码用 btoa（UTF-8 先 encodeURIComponent），解码用 atob（UTF-8 后 decodeURIComponent），解码忽略换行。例：printf hi | base64 → aGk=；printf aGk= | base64 -d → hi。' },
  type: { title: '命令类型查询', syn: 'type [-t] <命令...>', desc: '查询命令是 alias（别名）、builtin（内建）还是 keyword（关键字）。-t 简洁模式只输出类型名；默认输出说明文字。全部找到码 0，任一未找到码 1。例：type cd → cd 是 shell 内建；type -t ls → builtin。' },
  date: { title: '日期时间', syn: 'date [-u] [-d 时间串] [+格式]', desc: '显示/格式化日期时间。无格式串输出本地时间字符串；+格式串 按 strftime 展开：%Y 4位年、%y 2位年、%m 月、%d 日、%H 时、%M 分、%S 秒、%j 年中第几天(001-366)、%s Unix 时间戳、%w 数字星期(0-6,0=周日)、%A 星期全名、%a 星期缩写、%B 月名、%Z 时区名、%z 时区偏移、%% 百分号。-u 用 UTC；-d 解析时间串（YYYY-MM-DD 或 YYYY-MM-DD HH:MM:SS，纯日期当本地时间，字段一致性校验防 2023-02-29 误报有效）。例：date +%Y-%m-%d；date -d 2024-06-15 +"%H:%M:%S"。' },
  time: { title: '命令计时', syn: 'time <命令>', desc: '执行一条命令并报告耗时。计时信息（real/user/sys）输出到 stderr，子命令 stdout/err 透传，退出码取子命令码。args join 成命令字符串调 run 执行，故支持管道/重定向。user/sys 无法区分均报 0（bash 格式兼容）。例：time echo hi；time sleep 0.5。' },
  uname: { title: '系统信息', syn: 'uname [-a|-s|-n|-r|-m]', desc: '打印系统信息。-s 内核名 QieZiOS（默认）、-n 节点名 qiezios、-r 内核版本 1.0.0、-m 机器硬件名 x86_64、-a 全部。例：uname -a。' },
  uptime: { title: '运行时间', syn: 'uptime', desc: '显示当前时间、系统已运行时长、在线用户数与系统负载（模拟）。格式「HH:MM:SS up N, 1 user, load average: 0.00, 0.00, 0.00」。' },
  cal: { title: '日历', syn: 'cal [[月] 年]', desc: '显示日历。无参显示当月；单参数 > 31 当年份显示全年 12 个月、≤ 31 当月份显示同年该月；双参数为 月 年。中文月名「N月」，星期表头「日 一 二 三 四 五 六」。非法月年报错码 1。例：cal；cal 6 2024；cal 2024。' },
  nproc: { title: 'CPU 核数', syn: 'nproc', desc: '打印可用的 CPU 核数（取 navigator.hardwareConcurrency，兜底 8）。' },
  mktemp: { title: '创建临时文件', syn: 'mktemp [-d]', desc: '在 /tmp 下创建一个唯一命名的临时文件（默认）或目录（-d），返回其绝对路径。命名 .tmp_ + 随机串 + 时间戳防冲突；/tmp 不存在时自动创建。例：f=$(mktemp); echo data > $f。' },
  realpath: { title: '真实路径', syn: 'realpath <路径>', desc: '把给定路径解析为绝对路径，消解 . 和 ..（根目录 .. 不上溢）。相对路径基于当前工作目录。例：realpath /a/b/../c → /a/c；realpath ./x → /当前目录/x。' },
  printenv: { title: '打印环境变量', syn: 'printenv [变量...]', desc: '无参列出全部环境变量（KEY=VALUE 逐行）；带参逐行打印指定变量的值，任一未定义退出码 1。例：printenv USER；printenv HOME PATH。' },

  // M52：Shell 常用命令补全
  exit: { title: '退出 shell', syn: 'exit [退出码]', desc: '退出当前 shell 会话并关闭终端窗口。退出码默认 0；非数字参数也默认 0。Terminal 检测 exit 标志后调 sys.proc.close 关窗。例：exit；exit 5。' },
  history: { title: '命令历史', syn: 'history [-c|-d N] [N]', desc: '列出命令历史（格式「行号 命令」，行号右对齐 4 位）。-c 清空历史；-d N 删除第 N 条（1-based，超范围码 1）；带数字参数只显示最近 N 条。历史跨终端持久化（cmdHistory store）。例：history 10；history -c；history -d 3。' },
  df: { title: '磁盘空间', syn: 'df', desc: '显示文件系统磁盘使用情况。表头 Filesystem/1M-blocks/Used/Available/Use%/Mounted on，数据行 qzfs 报告虚拟磁盘容量、已用、可用与使用率（基于 VFS 节点统计）。例：df。' },
  du: { title: '目录大小', syn: 'du [-s] [路径]', desc: '递归统计目录或文件大小（文本按 content.length、二进制按 size）。-s 仅总计不列子项；无路径默认当前目录。输出格式「字节数\\t路径」。例：du -s /etc；du /tmp/file.txt。' },
  free: { title: '内存使用', syn: 'free', desc: '显示内存与交换空间使用情况。Mem 行取 navigator.deviceMemory（兜底 8GB）与 performance.memory（Chromium）估算；Swap 行恒 0（浏览器无交换）。例：free。' },
  pushd: { title: '压栈切目录', syn: 'pushd [目录]', desc: '将目录压入目录栈并切换。无参交换栈顶两项目录（bash 语义）；有参切到目标目录并压栈。栈初始含根目录。配合 popd/dirs 使用。例：pushd /tmp；pushd。' },
  popd: { title: '弹栈切回', syn: 'popd', desc: '弹出目录栈顶并切换到新栈顶目录。栈仅 1 项时报错码 1（bash：directory stack empty）。配合 pushd/dirs 使用。例：popd。' },
  dirs: { title: '显示目录栈', syn: 'dirs [-c]', desc: '显示当前目录栈（空格分隔，栈顶在最右）。-c 清空栈仅保留当前目录。例：dirs；dirs -c。' },
  pgrep: { title: '按名查进程', syn: 'pgrep <模式>', desc: '按命令名匹配进程并输出 pid（每行一个）。模式为子串匹配（大小写不敏感）。无模式码 2；无匹配码 1。例：pgrep terminal；pgrep shell。' },
  pkill: { title: '按名杀进程', syn: 'pkill <模式>', desc: '按命令名匹配并关闭进程。模式为子串匹配（大小写不敏感）。返回被杀进程数；无模式码 2。例：pkill terminal。' },
  timeout: { title: '超时执行', syn: 'timeout <秒> <命令>', desc: '在指定秒数内执行命令，超时则置中断标志杀掉并返回码 124。秒数 0 立即超时。命令支持管道/重定向（args join 后交 run 执行）。例：timeout 2 sleep 5；timeout 0 echo hi。' },
  file: { title: '文件类型', syn: 'file <文件...>', desc: '检测文件类型。文本（可打印字符占比 ≥ 80%）报「ASCII text」；否则报「data」。目录报「directory」。多文件逐行输出「路径: 类型」。例：file /etc/passwd；file /bin/true。' },
  command: { title: '直接执行命令', syn: 'command <命令> [参数...]', desc: '绕过别名和函数，直接按内建/外部命令查找执行。用于确保调用真实命令而非同名别名。-v 只打印命令路径不执行。例：command ls；command -v echo。' },
  builtin: { title: '执行内建命令', syn: 'builtin <命令> [参数...]', desc: '强制执行指定内建命令，绕过同名函数/别名。命令不存在报错码 1。例：builtin echo hello；builtin cd /tmp。' },

  // M53.1-10：文本处理与归档压缩
  sed: { title: '流编辑器', syn: 'sed [-n] 脚本 [文件]', desc: '按行过滤转换文本。支持 s/old/new/[g] 替换（默认每行首个，g 全局）、d 删除、p 打印（配 -n 只输出命中行）；地址：N 行号、$ 末行、/re/ 正则、N,M 范围。无文件读标准输入；无脚本/脚本无法解析码 2。例：sed s/a/b/g f.txt；seq 5 | sed -n 2,4p。' },
  awk: { title: '模式扫描处理', syn: 'awk [-F 分隔符] 程序 [文件...]', desc: '极简 AWK：程序由 BEGIN{}/END{}/模式{动作} 组成，动作仅 print。字段 $0 整行、$1..$N 分列，内建 NR 行号、NF 字段数；模式支持 /re/ 正则与 NR==N。-F 指定分隔符（默认空白）。无文件读标准输入；无程序码 2。例：ls -l | awk {print $1}；awk -F: {print $2} f.txt。' },
  join: { title: '关系连接', syn: 'join [-t 分隔符] [-1 N] [-2 N] [-a 1|2] <文件1> <文件2>', desc: '按公共字段连接两有序文件。默认首字段、空白分列、空格输出；-t 指定分隔符；-1/-2 指定各自连接字段；-a 1/-a 2 附带左/右文件未配对行。右文件同键只取首行（首匹配）。例：join a.txt b.txt；join -t, -1 2 -2 1 a.csv b.csv。' },
  tar: { title: '归档打包', syn: 'tar [c|x|t][zv] -f 归档 [文件...] [-C 目录]', desc: 'USTAR 归档。c 创建（目录递归，条目名 = 命令行所给路径）、x 解压（-C 指定目标目录，覆盖已存在文件，按字节探测文本/二进制还原；含 ../绝对路径的恶意条目跳过防 zip-slip）、t 列表；z 经 gzip 过滤（t/x 按魔数自动识别无需 -z）；v 详细（列表含权限串与大小、创建/解压回显条目名）。支持传统风格 tar cf。归档存为二进制文件。例：tar czf a.tgz dir/；tar xzf a.tgz -C /tmp。' },
  gzip: { title: 'gzip 压缩', syn: 'gzip [-dklv] <文件...>', desc: 'RFC 1952 压缩。f → f.gz 并删原文件（-k 保留）；.gz 已存在不覆盖码 1；-d 解压（gunzip 等价，还原按字节探测文本/二进制）；-l 列表压缩信息（压缩后/原始大小、压缩率、原名）；-v 回显结果。例：gzip big.log；gzip -dk big.log.gz。' },
  gunzip: { title: 'gzip 解压', syn: 'gunzip [-kv] <文件.gz...>', desc: '等价 gzip -d。把 .gz 还原为去后缀的原文件并删 .gz（-k 保留）；目标已存在不覆盖码 1。' },
  ln: { title: '创建链接', syn: 'ln [-s] [-f] <目标> [链接名]', desc: '-s 创建软链（可悬空；相对目标基于链接所在目录解析；cat/ls/test -e 透明跟随，test -L 识别链接本身）；默认硬链——VFS 树模型模拟为同内容/同权限副本（事后各自独立）。链接名缺省 = basename(目标)；落点是目录则放进其内；-f 强制覆盖已存在。例：ln -s /a.txt shortcut；ln -sf /a.txt shortcut。' },
  readlink: { title: '读链接目标', syn: 'readlink <链接...>', desc: '输出软链的目标串（最后一段不跟随，悬空链接也照输）。非链接报错码 1；缺参数码 2。例：readlink shortcut。' },
  wget: { title: '下载文件', syn: 'wget [-q] [-c] [-O 文件] <URL>', desc: '下载 URL 存为文件。默认文件名 = URL 末段（重名自动 .1/.2，wget 风格）；-O 指定输出（覆盖已存在）；-c 断点续传（发 Range 头并拼接已有字节）；-q 静默（默认输出「已保存」行）。服务器错误码 1 且不建文件；文本/二进制按字节自动识别。例：wget https://x/y.txt；wget -c -O big.bin URL。' },
  strings: { title: '提取可打印串', syn: 'strings [-n 长度] <文件...>', desc: '提取文件中的可打印 ASCII 串（0x20-0x7E），默认最小长度 4，-n 调整。常用于在二进制（如 .gz）里找内嵌文件名。例：strings a.gz；strings -n 8 blob.bin。' },
  hexdump: { title: '十六进制转储', syn: 'hexdump [-C] [-A x|d|o|n] <文件...>', desc: '规范格式转储：地址 + 每行 16 字节 hex + |ascii|（非打印字节显示为点）。默认即 -C 格式；-A 地址进制（x 十六进制默认、d 十进制、o 八进制、n 不显示地址与结束行）。例：hexdump -C f.bin；hexdump -A d f.bin。' },
  od: { title: '八进制转储', syn: 'od [-A x|d|o|n] [-t x1|c] <文件...>', desc: '传统字节转储。默认 -A o -t x1（八进制地址 + 十六进制字节）；-t c 字符型（可打印原样、\\n \\t \\r \\0 转义、其余 \\NNN 八进制）；-A 地址进制（n 不显示）。例：od -t c f.txt；od -A x f.bin。' },

  // M53.11-13：差异与同步
  diff: { title: '比较文件差异', syn: 'diff [-urq] <文件1> <文件2>', desc: '逐行比较两文件。相同无输出码 0、有差异码 1、出错码 2。默认 normal 格式（NcM/NaM/NdM + 「< 」「> 」行）；-u 输出 unified 格式（---/+++ 头 + @@ hunk，上下文 3 行，可直接喂给 patch）；-r 递归比较两目录（按相对路径对齐，单侧独有报「仅在 … 中存在」）；-q 只报「文件 X 和 Y 不同」。操作数为 - 时读标准输入。二进制文件只比较异同。例：diff -u a.txt b.txt | patch。' },
  patch: { title: '应用差异补丁', syn: 'patch [-pN] [--dry-run] [-i 补丁文件]', desc: '把 unified diff 补丁应用到文件（补丁来自 stdin 或 -i 文件）。-pN 剥掉补丁路径的前 N 段（如 -p1 剥 a/ b/ 前缀）；--dry-run 只校验不写盘（输出 checking file）。支持 --- /dev/null 新建文件、+++ /dev/null 删除文件（移入回收站）。hunk 先按声明行号定位，失配时按 GNU 偏移扫描找唯一匹配；全部 hunk 命中才落盘（原子），失败报 Hunk FAILED 码 1 且文件不变。无输入/补丁文件不存在/非法选项码 2。例：diff -u old new | patch；patch -p1 -i fix.diff。' },
  sync: { title: '同步刷盘', syn: 'sync', desc: '把所有挂起的持久化写立即刷入浏览器存储（localStorage/IndexedDB），对标 sync(2)。无输出，退出码恒 0。' },

  // 权限 / 用户
  chmod: { title: '改权限', syn: 'chmod <模式> <路径...>', desc: '设置权限位。模式支持八进制（644 / 755 / 600）或符号模式（[ugoa][+-=][rwx]，逗号多子句，省略 who = a）。如 chmod u+x s.sh、chmod go-w a.txt、chmod a=r f。' },
  chown: { title: '改属主', syn: 'chown <用户> <路径...>', desc: '设置文件/目录的属主。' },
  stat: { title: '查看元数据', syn: 'stat <路径>', desc: '显示名称/类型/大小/权限/属主/创建与修改时间。' },
  whoami: { title: '当前用户', syn: 'whoami', desc: '打印当前用户名。' },
  id: { title: '用户 uid/gid', syn: 'id [用户]', desc: '显示用户的 uid 与 gid（默认当前用户）。' },
  users: { title: '列出用户', syn: 'users', desc: '列出系统已知用户。' },
  su: { title: '切换用户', syn: 'su [用户]', desc: '切换当前 shell 的身份（无密码，单机隐喻）。无参数切到 root（提示符变 #）。' },
  sudo: { title: '以 root 运行', syn: 'sudo <命令>', desc: '以 root 身份执行一条命令，执行完恢复原身份。用于需要 root 的操作（如 useradd）。' },
  useradd: { title: '新建用户', syn: 'useradd <用户名>', desc: '新增一个用户（仅 root 可用，uid 从 1001 起）。会同步写入 /etc/passwd。' },

  // 进程 / 服务
  ps: { title: '进程快照', syn: 'ps', desc: '列出窗口进程（PID/PPID/状态/标题）。' },
  pstree: { title: '进程树', syn: 'pstree', desc: '以 init(0) 为根按父子关系画进程树。' },
  jobs: { title: '后台作业列表', syn: 'jobs', desc: '列出本 shell 用 & 启动的后台作业及状态（Running/Done/Failed）。' },
  fg: { title: '前台化作业', syn: 'fg [作业号]', desc: '等某个后台作业完成并显示其输出。无参数取最近一个仍在运行的作业。' },
  bg: { title: '后台运行作业', syn: 'bg [作业号]', desc: '提示作业在后台运行。本 shell 的 & 作业总是异步执行、无停止态，故 bg 仅作提示。' },
  wait: { title: '等待作业', syn: 'wait', desc: '阻塞直到所有仍在运行的后台作业完成。' },

  // 终端定时
  at: { title: '一次性定时', syn: 'at +<N>[s|m|h] <命令>  /  at -l  /  at -r <id>', desc: '在指定延时后执行一条命令（到点由定时器服务跑、结果以通知回报）。如 at +10s theme dark。-l 列出待执行任务、-r 取消。命令是普通 shell 命令（可含管道等）。' },
  atq: { title: '列出定时任务', syn: 'atq', desc: '等价于 at -l：列出排队中的一次性定时任务。' },
  crontab: { title: '循环定时', syn: 'crontab <间隔>[s|m|h] <命令>  /  crontab -l  /  crontab -r <id>', desc: '每隔一段时间循环执行一条命令（最小间隔 1s）。如 crontab 30s curl https://… 。-l 列出、-r 删除。简化版（用间隔而非 5 段 cron 表达式）。' },
  kill: { title: '发信号给进程', syn: 'kill [-9|-STOP|-CONT|-TERM] <pid>', desc: '默认 TERM 终止；-9/KILL 强制关闭；-STOP 挂起(最小化)；-CONT 恢复。' },
  systemctl: { title: '管理后台服务', syn: 'systemctl [list|status|start|stop|restart|enable|disable] [服务]', desc: '查看/控制后台服务（init）。enable/disable 持久化开机启动；start/stop 为运行时操作。' },
  pkg: { title: '远程 App 仓库', syn: 'pkg [list|search 词|install id|repo URL]', desc: '从远程仓库（catalog URL）浏览并安装 App（对标 apt）。list 列出、search 搜索、install 安装到「我的 App」、repo 查看/设置仓库源。也有图形界面「应用商店」。' },

  // 网络 / 环境 / 主题
  curl: { title: '抓取 URL', syn: 'curl [-i|-I] <url>', desc: '用浏览器 fetch 抓取一个 URL 并输出正文。-i 含状态行、-I 只看响应头。受同源/CORS 限制。' },
  fetch: { title: 'curl 的别名', syn: 'fetch [-i|-I] <url>', desc: '同 curl。' },
  hostname: { title: '主机名', syn: 'hostname', desc: '打印主机名（环境变量 HOSTNAME）。' },
  ai: { title: '问 AI', syn: 'ai <问题>（或 … | ai <指令>）', desc: '在命令行向 AI 提问，输出回答。可用管道把内容喂给它，如 cat 笔记.txt | ai 总结要点。和助手 App 共用同一个 AI 引擎。反过来，助手也能用 run_shell 跑这些命令。' },
  env: { title: '列环境变量', syn: 'env', desc: '打印所有环境变量（KEY=VALUE）。' },
  export: { title: '设环境变量', syn: 'export KEY=VALUE', desc: '设置环境变量（当前 shell 会话内）。要持久化可写进 /etc/profile。' },
  unset: { title: '删环境变量', syn: 'unset KEY...', desc: '删除一个或多个环境变量。' },
  local: { title: '函数局部变量', syn: 'local [名[=值]...]', desc: '在函数内声明局部变量：函数返回后自动恢复原值（同名全局被遮蔽）或删除（新声明）。只能在函数内使用，函数外调用报错码 1。无参等价于不操作。' },
  set: { title: 'shell 选项开关', syn: 'set [-e|+e]', desc: '无参列出全部环境变量（按名排序）。set -e 开严格模式：任何命令失败（非豁免上下文）立即中止脚本；set +e 关闭。豁免上下文：if/while/until 条件、&&/|| 非末段、! 取反。' },
  eval: { title: '二次执行字符串', syn: 'eval [参数...]', desc: '把所有参数拼成一条命令再执行一次（共享当前环境）。典型用途：先拼出命令字符串再跑，如 cmd="echo hi"; eval $cmd。嵌套上限 25 层防自引用死循环（x="eval $x" 会报嵌套过深）。' },
  alias: { title: '命令别名', syn: "alias [名=值]", desc: "给命令起别名（持久化、跨终端）。无参列出全部；alias ll='ls -l' 定义；之后输入 ll 即展开。" },
  unalias: { title: '删别名', syn: 'unalias <名>', desc: '删除一个命令别名。' },
  which: { title: '命令位置', syn: 'which <命令>', desc: '若命令是内置命令，按 PATH 显示其路径（如 /bin/ls）。' },
  source: { title: '执行脚本', syn: 'source <文件>（或 . <文件>）', desc: '执行一个文件里的命令（整文件解释、支持多行 if/for/while，共享当前 shell 环境）。开终端时会自动 source /etc/profile。' },
  sh: { title: '跑脚本', syn: 'sh <脚本文件>（或 ./脚本.sh）', desc: '执行一个脚本文件，支持多行控制流。sh/source 等价（共享当前环境）；./文件 直接运行需可执行权限位（chmod +x），无权限退出码 126。脚本结束会触发 EXIT 陷阱。' },
  read: { title: '读入变量', syn: 'read [-r] [-p 提示] 变量...', desc: '从标准输入读一行，按 IFS（默认空白）切分依次赋给变量；剩余字段并入最后一个变量。-r 不处理反斜杠转义（默认反斜杠是行延续）。-p 指定提示串（先写 stderr）。无输入时退出码非 0。配合管道与重定向使用（如 cat f | while read line; do …; done）。' },
  test: { title: '条件判断', syn: 'test 表达式（或 [ 表达式 ]）', desc: '判断条件并返回退出码（0真/1假），给 if/while 用。文件测试：-f 普通文件、-d 目录、-e 存在、-r/-w/-x 权限、-s 非空、-L 符号链接、-nt 新于、-ot 旧于（按 mtime 比较）。字符串：-z 空、-n 非空、= == 相等、!= 不等。数值：-eq/-ne/-lt/-le/-gt/-ge。其他：-v 变量已设、前导 ! 取反。' },
  '[[': { title: '扩展条件判断', syn: '[[ 表达式 ]]', desc: 'test 的增强版：支持 && || 组合多个条件、==/!= 右侧通配模式（如 [[ $f == *.txt ]]）、=~ 正则匹配（如 [[ $s =~ ^[0-9]+$ ]]）、< > 字典序比较，以及 test 的全部单目/双目算符（含 -v/-s/-L/-nt/-ot）。表达式内不做分词与通配展开，写起来更安全。' },
  trap: { title: '信号陷阱', syn: "trap [命令 信号...]（或 trap - 信号...）", desc: '注册/查看信号处理器。支持 INT（Ctrl+C，或 2/SIGINT）与 EXIT（脚本结束，或 0）。无参列举已设陷阱；trap - SIG 或 trap \'\' SIG 重置。INT 陷阱在 Ctrl+C 中断整条命令后触发一次；EXIT 陷阱在最外层 ./脚本 结束时触发（source 不触发）。' },
  true: { title: '恒真', syn: 'true', desc: '什么都不做，退出码 0。常用作占位或无限循环条件（while true）。' },
  false: { title: '恒假', syn: 'false', desc: '什么都不做，退出码 1。常用于测试条件分支。' },
  if: { title: '条件', syn: 'if 条件; then …; [elif 条件; then …;] [else …;] fi', desc: '按条件命令的退出码（0=真）选择执行分支。例：if test -f a.txt; then echo 有; else echo 无; fi' },
  for: { title: '循环（遍历 / 算术）', syn: 'for 变量 in 词…; do …; done  |  for ((init; cond; step)); do …; done', desc: '两种形式：(1) 经典 for-in：遍历词表，每次把变量设为一个词后执行循环体。词表支持 $VAR、花括号 {a,b} 与路径通配。(2) C 风格算术 for：for ((init; cond; step)); do …; done。init/step 是算术表达式（可含赋值副作用 $((x=5))、自增 i++），cond 非零为真（空 cond 视为真，等同 while true）。例：for ((i=0; i<3; i++)); do echo $i; done 输出 0 1 2；支持 break/continue 与嵌套。' },
  while: { title: '循环（条件）', syn: 'while 条件; do …; done', desc: '只要条件命令退出码为 0 就反复执行循环体（有最大迭代保护）。' },
  until: { title: '循环（条件取反）', syn: 'until 条件; do …; done', desc: '与 while 相反：只要条件命令退出码非 0 就反复执行循环体，条件转真即停。' },
  break: { title: '跳出循环', syn: 'break [n]', desc: '跳出当前循环；带 n 跳出 n 层嵌套循环。循环外使用仅警告、不致命（退出码 0）。' },
  continue: { title: '跳过本次迭代', syn: 'continue [n]', desc: '跳过本次迭代的剩余语句进入下一迭代；带 n 作用于往外第 n 层循环。' },
  case: { title: '模式分支', syn: 'case 词 in [模式|模式) 分支 ;;]… esac', desc: '把词逐个按通配模式（* ? [a-z]）匹配，命中即执行对应分支（;; 结束）。例：case $f in *.txt) echo 文本 ;; *) echo 其他 ;; esac' },
  return: { title: '从函数/脚本返回', syn: 'return [退出码]', desc: '提前退出当前函数或 source 执行的脚本，可指定退出码（默认上一条命令的退出码）。' },
  '((': { title: '算术命令', syn: '(( 表达式 ))', desc: '求值算术表达式（与 $(( )) 同款语法，但 (( )) 是命令而非展开）。退出码：表达式结果非 0 为真(0)、为 0 为假(1)，无 stdout。支持赋值副作用（((i++))、((x+=2))）。常作 if/while 条件或与 && || 串联：(( 1 < 2 )) && echo yes。注意 for ((init; cond; step)) 是算术 for 循环，不走此通道。' },
  '{': { title: '命令分组', syn: '{ 命令1; 命令2; … }', desc: '在当前 shell 执行一组命令（{ 后需空白/换行，} 前需 ;/换行）。与 ( ) 子 shell 的区别：{ } 内的 cd/export/赋值会影响当前 shell 环境。退出码 = 最后一条命令的码。可含控制结构（{ if …; fi }）。已知限制：} 后接重定向(} > f)或连接符(} && cmd)暂不支持。' },
  '(': { title: '子 shell', syn: '( 命令1; 命令2; … )', desc: '在子 shell 中执行一组命令（fork 语义）：cd/export/赋值不回流父 shell，但子 shell 的 stdout/stderr 流回父、退出码回流父（( false ) → 父 $? = 1）。可含控制结构/管道。Ctrl+C 可中断子 shell 内的失控循环。与 { } 分组对照：{ } 影响当前环境，( ) 隔离环境。已知限制：) 后接重定向() > f)或连接符() && cmd)暂不支持。' },
  theme: { title: '改主题', syn: 'theme dark|light|#hex', desc: '切换明暗或设置主色。无参数显示当前主题。' },
  clear: { title: '清屏', syn: 'clear', desc: '清空终端输出（也可按 Ctrl+L）。' },
  '<(': { title: '进程替换', syn: '命令 <(内部命令) [<(内部命令)...]', desc: '把内部命令的 stdout 落临时文件（/tmp/.psub_*），路径作为参数传给外层命令。如 cat <(echo a) <(echo b) 拼接两段；grep h <(echo hello) 过滤。内部命令在子 shell 执行（cd/export 不影响父 shell），支持管道/变量展开/控制流。Ctrl+C 可中断内部失控循环。>(cmd) 暂未实现。' },
};
